services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: pdfmalwareproject-web  # Specify the desired image name here
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
